name: Destroy SageMaker Inference Endpoint

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ENDPOINT_NAME: ${{ vars.ENDPOINT_NAME }}

jobs:
  destroy:
    name: Destroy SageMaker Inference Endpoint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Delete SageMaker Inference Endpoint
        run: |
          aws sagemaker delete-endpoint --endpoint-name $ENDPOINT_NAME

      - name: Delete SageMaker Model
        run: |
          aws sagemaker delete-model --model-name $ENDPOINT_NAME-model

      - name: Delete SageMaker Endpoint Configuration
        run: |
          aws sagemaker delete-endpoint-config --endpoint-config-name $ENDPOINT_NAME
