name: Deploy to SageMaker

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  MODEL_NAME_TAR: ${{ vars.MODEL_NAME_TAR }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  ENDPOINT_NAME: ${{ vars.ENDPOINT_NAME }}
  INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
  SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
  MODEL_CODE_PATH: paint-model/code

jobs:
  check-cache:
    name: Check Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.MODEL_CODE_PATH }}
            devops
      - name: Get cache
        uses: actions/cache@v4
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*.py', '**/*.yml', '**/*.txt') }}
          path: ${{ env.MODEL_CODE_PATH }}
          lookup-only: true

  prepare:
    needs: check-cache
    name: Prepare and push to S3 if changed
    runs-on: ubuntu-latest
    if: ${{ needs.check-cache.outputs.cache-hit != 'true' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create tar.gz of the model folder
        run: tar --exclude='.DS_Store' -czvf $MODEL_NAME_TAR -C $MODEL_CODE_PATH .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Upload model to S3
        run: aws s3 cp $MODEL_NAME_TAR s3://$S3_BUCKET_NAME/$MODEL_NAME_TAR

  deploy:
    name: Deploy to SageMaker
    runs-on: ubuntu-latest
    needs: [check-cache, prepare]
    if: ${{ needs.check-cache.outputs.cache-hit != 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            devops

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r devops/requirements.txt

      - name: Deploy to SageMaker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: $AWS_REGION
          S3_BUCKET_NAME: $S3_BUCKET_NAME
          ENDPOINT_NAME: $ENDPOINT_NAME
          MODEL_NAME_TAR: $MODEL_NAME_TAR
          SAGEMAKER_ROLE_ARN: $SAGEMAKER_ROLE_ARN
          INSTANCE_TYPE: $INSTANCE_TYPE
          MODEL_CODE_PATH: $MODEL_CODE_PATH
        run: python devops/deploy.py
