name: Typescript React - Vite build + deploy

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mgxs-gnss/actions/setup@v1.3
        name: Build
        with:
          artifact-name: "build"
          artifact-path: "./build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact and deploy
        uses: mgxs-gnss/actions/deploy@v1.3
        with:
          artifact-name: "build"
          artifact-path: "./build"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_cloudfront: ${{ secrets.AWS_CLOUDFRONT_ID }}
